"""
The shop scene with the animated shopkeeper. Input: the parts placed on the 2000×2800 reference canvas by
  python3 tools/boss/fit-parts.py shopkeeper '<plan>' && python3 tools/boss/place-parts.py shopkeeper
(tools/boss/source/shopkeeper/{raw,placed}). Every layer is cropped to its own box, scaled for phones and written to
public/assets/shop/v2/<layer>.webp; their boxes (percent of the canvas) go to src/client/art/shop-data.ts.
"""
import json
import numpy as np
from PIL import Image

D = "tools/boss/source/shopkeeper"
OUT = "public/assets/shop/v2"
W, H = 2000, 2800
K = 0.6                                  # 2000 px → 1200 px: sharp on a phone at 3× density
LAYERS = ["room", "lamp", "drinks", "rack", "torso", "armR", "armL", "head", "sclera", "iris", "lids", "cigarette", "counter", "weapons", "fist"]
import os
os.makedirs(OUT, exist_ok=True)
fits = json.load(open(f"{D}/raw/fit.json"))
data = {}
for n in LAYERS:
    a = np.array(Image.open(f"{D}/placed/{n}.png").convert("RGBA"))
    a[a[:, :, 3] < 24] = 0              # stray half-transparent pixels around the cut-outs
    if n == "counter":
        a[:1500, :, 3] = 0               # junk above the counter top
    if n == "room":
        box = (0, 0, W, H)
    else:
        ys, xs = np.nonzero(a[:, :, 3] > 0)
        box = (max(0, xs.min() - 4), max(0, ys.min() - 4), min(W, xs.max() + 5), min(H, ys.max() + 5))
    im = Image.fromarray(a).crop(box)
    im = im.resize((max(1, round(im.width * K)), max(1, round(im.height * K))), Image.LANCZOS)
    if n == "room":
        im.convert("RGB").save(f"{OUT}/{n}.webp", quality=82, method=6)
    else:
        im.save(f"{OUT}/{n}.webp", quality=86, method=6)
    x0, y0, x1, y1 = box
    data[n] = {"left": round(x0 / W * 100, 3), "top": round(y0 / H * 100, 3), "width": round((x1 - x0) / W * 100, 3), "height": round((y1 - y0) / H * 100, 3)}
    print(n, im.size, data[n])
# the lit end of the cigarette (on the face sheet) → canvas percent, for the smoke
h = fits["head"]
tip = (420, 802)
smoke = {"x": round((h["tx"] + tip[0] * h["s"]) / W * 100, 2), "y": round((h["ty"] + tip[1] * h["s"]) / H * 100, 2)}
# the neck (head sway pivot) and the waist (breathing pivot), canvas percent
neck = {"x": round((h["tx"] + 490 * h["s"]) / W * 100, 2), "y": round((h["ty"] + 820 * h["s"]) / H * 100, 2)}
ts = "/* generated by tools/shop/build-shop.py — boxes of the shop layers in percent of the 2000×2800 canvas */\n"
ts += "export type ShopLayer = { left: number; top: number; width: number; height: number };\n"
ts += f"export const SHOP_ART = {{\n  aspect: \"2000 / 2800\",\n  layers: {json.dumps(data, indent=2)} as Record<string, ShopLayer>,\n  smoke: {json.dumps(smoke)},\n  neck: {json.dumps(neck)},\n}};\n"
open("src/client/art/shop-data.ts", "w").write(ts)
print("smoke", smoke, "neck", neck)
