"""
Animated boss rigs from the artist's layers: tools/boss/source/<boss>/{body,head,eyes,eyes-closed,foreL,foreR}.png
(all on one canvas, in place) → public/bosses/<boss>/rig/<part>.webp (trimmed, half size) + src/client/art/boss-rig-data.ts.
Pivots: head — bottom of the neck; forearms — the elbow (the end that joins the body).
"""
import os, glob, json
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SCALE = 0.5
PARTS = ["body", "foreL", "foreR", "head", "eyes", "eyes-closed"]
# which edge of the part joins the parent: (axis, side) — y/bottom for head and left forearm, x/right for the right one
JOINT = {"head": ("y", "max"), "foreL": ("y", "max"), "foreR": ("x", "max")}

out = {}
for d in sorted(glob.glob(os.path.join(HERE, "source", "*"))):
    boss = os.path.basename(d)
    dest = os.path.join(ROOT, "public", "bosses", boss, "rig")
    os.makedirs(dest, exist_ok=True)
    rig = {}
    W = H = None
    for p in PARTS:
        f = os.path.join(d, p + ".png")
        if not os.path.exists(f):
            continue
        im = np.array(Image.open(f).convert("RGBA"))
        H, W = im.shape[:2]
        a = im[:, :, 3]
        a[a < 30] = 0
        im[a == 0, :3] = 0
        ys, xs = np.nonzero(a)
        x0, y0, x1, y1 = xs.min() - 3, ys.min() - 3, xs.max() + 4, ys.max() + 4
        crop = Image.fromarray(im[max(0, y0):y1, max(0, x0):x1])
        w, h = round(crop.width * SCALE), round(crop.height * SCALE)
        crop.resize((w, h), Image.LANCZOS).save(os.path.join(dest, p + ".webp"), "WEBP", quality=86, method=4)
        r = {"x": round(max(0, x0) * SCALE, 1), "y": round(max(0, y0) * SCALE, 1), "w": w, "h": h}
        if p in JOINT:
            axis, _ = JOINT[p]
            m = a > 128
            if axis == "y":
                band = ys.max() - (ys.max() - ys.min()) * 0.12
                sel = np.nonzero(m & (np.arange(H)[:, None] >= band))
            else:
                band = xs.max() - (xs.max() - xs.min()) * 0.15
                sel = np.nonzero(m & (np.arange(W)[None, :] >= band))
            r["pivot"] = [round(sel[1].mean() * SCALE, 1), round(sel[0].mean() * SCALE, 1)]
        rig[p] = r
    out[boss] = {"w": round(W * SCALE), "h": round(H * SCALE), "parts": rig}
    print(boss, json.dumps(rig))
ts = "/* Generated by tools/boss/build-boss.py — do not edit by hand. */\n"
ts += "export const BOSS_RIGS: Record<string, { w: number; h: number; parts: Record<string, { x: number; y: number; w: number; h: number; pivot?: readonly number[] }> }> = " + json.dumps(out, indent=2) + ";\n"
open(os.path.join(ROOT, "src", "client", "art", "boss-rig-data.ts"), "w").write(ts)
