"""Computer window: tools/scene/source/pc/{case,gpu,cooler,psu}.png (one shared 1312×1199 canvas, parts drawn in place)
→ public/assets/pc/case.webp (trimmed to the case) + public/assets/pc/<part>.webp (trimmed part layers)
and their boxes in % of the case → src/client/art/pc-data.ts."""
import os, json
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(HERE, "source", "pc")
OUT = os.path.join(ROOT, "public", "assets", "pc")
os.makedirs(OUT, exist_ok=True)
CASE_W = 760  # px of the published case picture
PARTS = {"pc-gpu": "gpu", "pc-cooler": "cooler", "pc-psu": "psu"}
# tap zones (source canvas px) where the layer's own box is too wide: the PSU layer carries its cables across the case
HOT = {"pc-psu": (88, 829, 600, 1064)}


def load(name):
    a = np.array(Image.open(os.path.join(SRC, name + ".png")).convert("RGBA"))
    a[a[:, :, 3] < 40] = 0
    return a


def bbox(a, pad=2):
    ys, xs = np.nonzero(a[:, :, 3])
    return max(0, xs.min() - pad), max(0, ys.min() - pad), xs.max() + 1 + pad, ys.max() + 1 + pad


case = load("case")
cx0, cy0, cx1, cy1 = bbox(case)
cw, ch = cx1 - cx0, cy1 - cy0
k = CASE_W / cw
im = Image.fromarray(case[cy0:cy1, cx0:cx1]).resize((CASE_W, round(ch * k)), Image.LANCZOS)
im.save(os.path.join(OUT, "case.webp"), "WEBP", quality=84, method=4)
print("case", im.size, os.path.getsize(os.path.join(OUT, "case.webp")) // 1024, "KB")


def pct(box):
    x0, y0, x1, y1 = box
    return {"x": round((x0 - cx0) / cw * 100, 2), "y": round((y0 - cy0) / ch * 100, 2),
            "w": round((x1 - x0) / cw * 100, 2), "h": round((y1 - y0) / ch * 100, 2)}


data = {"aspect": round(cw / ch, 4), "parts": {}}
for pid, name in PARTS.items():
    a = load(name)
    box = bbox(a)
    x0, y0, x1, y1 = box
    part = Image.fromarray(a[y0:y1, x0:x1])
    part = part.resize((round(part.width * k * 1.4), round(part.height * k * 1.4)), Image.LANCZOS)  # a bit sharper for the window
    part.save(os.path.join(OUT, name + ".webp"), "WEBP", quality=86, method=4)
    data["parts"][pid] = {"src": f"/assets/pc/{name}.webp", "box": pct(box), "hot": pct(HOT.get(pid, box))}
    print(pid, part.size, data["parts"][pid])

ts = "/* Generated by tools/scene/build-pc.py — do not edit by hand. Boxes in % of the case picture. */\n"
ts += "export const PC_ART = " + json.dumps(data, indent=2) + " as const;\n"
open(os.path.join(ROOT, "src", "client", "art", "pc-data.ts"), "w").write(ts)
