"""
Home scene assets from the artist's drawings (tools/scene/source):
  room-<id>.png   — opaque background, 1060×1484 (the scene canvas)
  desk-N / monitor-N / pc-N / seat-N.png — one object per file on its own canvas (any size, transparent)
Objects are trimmed and resized to the size they take in the scene (see src/content/home-scene.ts),
then saved as WebP to public/assets/home/.
"""
import os, re, sys
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(ROOT, "public", "assets", "home")
os.makedirs(OUT, exist_ok=True)
# widths in scene units (the seat in rig units, it lives in the character's space); ×1.5 for sharp phones
# sky behind the penthouse window: top and height in scene units (keep in sync with src/content/home-scene.ts ROOM_SKY)
SKY_Y, SKY_H = 40, 880
WIDTH = {"desk": 920, "monitor": 250, "pc": 150, "seat": 360}
DESKS = {}
for f in sorted(os.listdir(os.path.join(HERE, "source"))):
    name, ext = os.path.splitext(f)
    # only the home scene's own files (the arena, yard, shop… have their own build scripts)
    if ext != ".png" or not re.match(r"(room-|(desk|monitor|pc|seat)-[a-z0-9]+$)", name):
        continue
    im = Image.open(os.path.join(HERE, "source", f))
    if name.startswith("room-"):
        # a room with a see-through window (alpha) keeps it: the sky is drawn behind (penthouse)
        has_alpha = im.mode in ("RGBA", "LA") and im.getchannel("A").getextrema()[0] < 250
        (im.convert("RGBA") if has_alpha else im.convert("RGB")).save(os.path.join(OUT, name + ".webp"), "WEBP", quality=82, method=6)
        if has_alpha and os.path.exists(os.path.join(HERE, "source", "sky", name[5:] + "-sky.png")):
            # the panorama behind the window: SKY_H scene units tall, plus a flat copy (room over sky) for the blurred backdrop
            sky = Image.open(os.path.join(HERE, "source", "sky", name[5:] + "-sky.png")).convert("RGB")
            sw = round(sky.width * SKY_H / sky.height)
            sky = sky.resize((sw, SKY_H), Image.LANCZOS)
            sky.save(os.path.join(OUT, name[5:] + "-sky.webp"), "WEBP", quality=78, method=6)
            flat = Image.new("RGB", im.size, (40, 30, 30))
            flat.paste(sky.crop((0, 0, im.width, SKY_H)), (0, SKY_Y))
            flat.paste(im.convert("RGBA"), (0, 0), im.convert("RGBA"))
            flat.save(os.path.join(OUT, name + "-flat.webp"), "WEBP", quality=70, method=6)
            print(name[5:] + "-sky", sky.size)
    else:
        kind = re.sub(r"-[a-z0-9]+$", "", name)
        im = im.convert("RGBA"); a = im.getchannel("A").point(lambda v: 0 if v < 30 else v); im.putalpha(a)
        im = im.crop(im.getbbox())
        w = round(WIDTH[kind] * 1.5); h = round(im.height * w / im.width)
        im.resize((w, h), Image.LANCZOS).save(os.path.join(OUT, name + ".webp"), "WEBP", quality=88, method=6)
        print(name, "aspect h/w =", round(im.height / im.width, 4))
        if kind in ("desk", "monitor"): DESKS[name] = round(im.height / im.width, 4)
    print(name, os.path.getsize(os.path.join(OUT, name + ".webp")) // 1024, "KB")

# chairs: drawn on the 2000×2800 character canvas in place (like the clothes) → trimmed, half size, and their place
# in the 1000×1400 rig coordinates
CHAIRS = {}
CHAIR_BOX = (122, 389, 1877, 2733)  # chair-1 on the character canvas: where a chair stands
for f in sorted(os.listdir(os.path.join(HERE, "source"))):
    m = re.match(r"(chair-\d+)\.png$", f)
    if not m:
        continue
    im = Image.open(os.path.join(HERE, "source", f)).convert("RGBA")
    a = im.getchannel("A").point(lambda v: 0 if v < 30 else v); im.putalpha(a)
    if im.size != (2000, 2800):
        # drawn on its own canvas: stand it where the first chair stands (same height, wheels on the same line, centred)
        im = im.crop(im.getbbox())
        H = CHAIR_BOX[3] - CHAIR_BOX[1]
        W = round(im.width * H / im.height)
        canvas = Image.new("RGBA", (2000, 2800))
        canvas.alpha_composite(im.resize((W, H), Image.LANCZOS), (1000 - W // 2, CHAIR_BOX[1]))
        im = canvas
    x0, y0, x1, y1 = im.getbbox()
    im = im.crop((x0, y0, x1, y1))
    w, h = round((x1 - x0) / 2), round((y1 - y0) / 2)
    im.resize((w, h), Image.LANCZOS).save(os.path.join(OUT, m.group(1) + ".webp"), "WEBP", quality=88, method=6)
    CHAIRS[m.group(1)] = {"x": x0 / 2, "y": y0 / 2, "w": w, "h": h}
    print(m.group(1), CHAIRS[m.group(1)])

# desks and monitors: picture aspect (h/w) → the room scene places them by level
import json
ts = "/* Generated by tools/scene/build-scene.py — do not edit by hand. Aspect h/w of each desk and monitor picture. */\n"
ts += "export const ART_ASPECT: Record<string, number> = " + json.dumps(DESKS) + ";\n"
ts += "/** chairs in rig coordinates (1000×1400): drawn behind the seated character */\n"
ts += "export const CHAIR_FIT: Record<string, { x: number; y: number; w: number; h: number }> = " + json.dumps(CHAIRS) + ";\n"
open(os.path.join(ROOT, "src", "client", "art", "desk-data.ts"), "w").write(ts)
