"""
Builds the seated player rig from the artist's parts.
Input: tools/rig/source/v2/<part>.png — every part on the same 2000×2800 transparent canvas, in place
(the torso layer includes the legs; face parts — eyes, pupils, brows, eyes-closed — ride on the head).
The first, broader character is kept in tools/rig/source/v1/.
Output: public/assets/hero/<part>.webp (trimmed, half size) + src/client/art/rig-data.ts (positions, pivots).
Pivots are found automatically where a child part overlaps its parent.
"""
import os, json
import numpy as np
from PIL import Image
import cv2

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(HERE, "source", "v2")
OUT = os.path.join(ROOT, "public", "assets", "hero")
SCALE = 0.5
PARTS = ["torso", "head", "armUL", "armUR", "foreL", "foreR", "eyes", "pupils", "brows", "eyes-closed"]
JOINTS = {  # child: parent
    "head": "torso", "armUL": "torso", "armUR": "torso", "foreL": "armUL", "foreR": "armUR",
}
os.makedirs(OUT, exist_ok=True)
data, masks = {}, {}
for p in PARTS:
    im = np.array(Image.open(os.path.join(SRC, p + ".png")).convert("RGBA"))
    a = im[:, :, 3]
    a[a < 40] = 0  # drop near-invisible haze
    # remove stray specks: keep components larger than 400 px
    n, lab, st, _ = cv2.connectedComponentsWithStats((a > 0).astype(np.uint8))
    for i in range(1, n):
        if st[i][4] < (20 if p in ("pupils", "eyes-closed", "brows", "eyes") else 400): a[lab == i] = 0
    im[:, :, 3] = a
    im[a == 0, :3] = 0
    masks[p] = a > 128
    ys, xs = np.nonzero(a)
    x0, y0, x1, y1 = xs.min() - 4, ys.min() - 4, xs.max() + 5, ys.max() + 5
    crop = Image.fromarray(im[y0:y1, x0:x1])
    w, h = round(crop.width * SCALE), round(crop.height * SCALE)
    crop.resize((w, h), Image.LANCZOS).save(os.path.join(OUT, p + ".webp"), "WEBP", quality=90, method=6)
    data[p] = {"x": round(x0 * SCALE, 1), "y": round(y0 * SCALE, 1), "w": w, "h": h}
for child, parent in JOINTS.items():
    o = masks[child] & masks[parent]
    ys, xs = np.nonzero(o)
    data[child]["pivot"] = [round(xs.mean() * SCALE, 1), round(ys.mean() * SCALE, 1)]
ts = "/* Generated by tools/rig/build-rig.py — do not edit by hand. Coordinates: 1000×1400 rig canvas. */\n"
ts += "export const RIG = " + json.dumps(data, indent=2) + " as const;\n"
open(os.path.join(ROOT, "src", "client", "art", "rig-data.ts"), "w").write(ts)
for p in PARTS: print(p, data[p], os.path.getsize(os.path.join(OUT, p + ".webp")) // 1024, "KB")
