// Generated by scripts/skin-manifest.mjs — do not edit. Lists pictures present in public/skin.
export const SKIN_FILES: Record<string, string> = {
  "bosses/chill-guy": "bosses/chill-guy.webp?v=4c5b25c5",
  "bosses/chill-house": "bosses/chill-house.webp?v=10436404"
};
