/* Generated by tools/boss/build-boss.py — do not edit by hand. */
export const BOSS_RIGS: Record<string, { w: number; h: number; parts: Record<string, { x: number; y: number; w: number; h: number; pivot?: readonly number[] }> }> = {
  "datsik": {
    "w": 1180,
    "h": 1400,
    "parts": {
      "body": {
        "x": 175.0,
        "y": 488.0,
        "w": 832,
        "h": 912
      },
      "foreL": {
        "x": 89.5,
        "y": 561.5,
        "w": 270,
        "h": 517,
        "pivot": [
          225.5,
          1040.2
        ]
      },
      "foreR": {
        "x": 475.0,
        "y": 847.0,
        "w": 528,
        "h": 324,
        "pivot": [
          956.4,
          1069.9
        ]
      },
      "head": {
        "x": 295.0,
        "y": 18.5,
        "w": 540,
        "h": 542,
        "pivot": [
          576.2,
          517.2
        ]
      },
      "eyes": {
        "x": 412.0,
        "y": 256.0,
        "w": 222,
        "h": 77
      },
      "eyes-closed": {
        "x": 407.5,
        "y": 258.0,
        "w": 206,
        "h": 58
      }
    }
  }
};
