/* Generated by tools/boss/build-boss.py — do not edit by hand. */
export const BOSS_RIGS: Record<string, { w: number; h: number; parts: Record<string, { x: number; y: number; w: number; h: number; pivot?: readonly number[] }> }> = {
  "datsik": {
    "w": 1180,
    "h": 1400,
    "parts": {
      "body": {
        "x": 175.0,
        "y": 488.0,
        "w": 832,
        "h": 912
      },
      "foreL": {
        "x": 89.5,
        "y": 561.5,
        "w": 270,
        "h": 517,
        "pivot": [
          225.5,
          1040.2
        ]
      },
      "foreR": {
        "x": 475.0,
        "y": 847.0,
        "w": 528,
        "h": 324,
        "pivot": [
          956.4,
          1069.9
        ]
      },
      "head": {
        "x": 295.0,
        "y": 18.5,
        "w": 540,
        "h": 542,
        "pivot": [
          576.2,
          517.2
        ]
      },
      "eyes": {
        "x": 412.0,
        "y": 256.0,
        "w": 222,
        "h": 77
      },
      "eyes-closed": {
        "x": 407.5,
        "y": 258.0,
        "w": 206,
        "h": 58
      }
    }
  },
  "datsik-beaten": {
    "w": 1180,
    "h": 1400,
    "parts": {
      "body": {
        "x": 175.5,
        "y": 487.0,
        "w": 834,
        "h": 913
      },
      "foreL": {
        "x": 89.0,
        "y": 561.0,
        "w": 224,
        "h": 518,
        "pivot": [
          224.2,
          1040.3
        ]
      },
      "foreR": {
        "x": 475.5,
        "y": 848.0,
        "w": 527,
        "h": 324,
        "pivot": [
          956.2,
          1069.4
        ]
      },
      "head": {
        "x": 293.5,
        "y": 19.0,
        "w": 538,
        "h": 538,
        "pivot": [
          575.3,
          515.5
        ]
      },
      "eyes": {
        "x": 408.5,
        "y": 253.5,
        "w": 228,
        "h": 92
      },
      "eyes-closed": {
        "x": 403.5,
        "y": 253.5,
        "w": 212,
        "h": 70
      }
    }
  }
};
