/* Generated by tools/scene/build-scene.py — do not edit by hand. Aspect h/w of each desk and monitor picture. */
export const ART_ASPECT: Record<string, number> = {"desk-001": 0.4031, "desk-002": 0.4173, "desk-003": 0.4043, "desk-004": 0.4094, "monitor-center": 0.7926, "monitor-left": 1.017, "monitor-right": 0.9905};
