/* Generated by tools/scene/build-scene.py — do not edit by hand. Aspect h/w of each desk and monitor picture. */
export const ART_ASPECT: Record<string, number> = {"desk-001": 0.4031, "desk-002": 0.4173, "desk-003": 0.4043, "desk-004": 0.4094, "monitor-1": 1.0, "monitor-center": 0.7926, "monitor-left": 1.017, "monitor-right": 0.9905};
/** chairs in rig coordinates (1000×1400): drawn behind the seated character */
export const CHAIR_FIT: Record<string, { x: number; y: number; w: number; h: number }> = {"chair-1": {"x": 61.0, "y": 194.5, "w": 878, "h": 1172}, "chair-2": {"x": 78.5, "y": 194.5, "w": 843, "h": 1172}};
