/* Generated by tools/scene/build-scene.py — do not edit by hand. Aspect h/w of each desk picture. */
export const DESK_ASPECT: Record<string, number> = {"desk-001": 0.3932, "desk-002": 0.4079, "desk-003": 0.3956, "desk-004": 0.3997};
