/* Generated by tools/rig/build-held.py — do not edit by hand. Rig coordinates (1000×1400). */
/** things held in the left hand (HAND slot): the hand with the thing, and its puppet-warp frames */
export const HELD_FIT: Record<string, { x: number; y: number; w: number; h: number; frames: number }> = {
  "bottle-komandate": {
    "x": 529.0,
    "y": 726.0,
    "w": 244,
    "h": 308,
    "frames": 10
  }
};
