/* Generated by tools/rig/build-held.py — do not edit by hand. Rig coordinates (1000×1400). */
/** things held in the left hand (HAND slot): the hand with the thing */
export const HELD_FIT: Record<string, { x: number; y: number; w: number; h: number }> = {
  "bottle-komandate": {
    "x": 539.0,
    "y": 736.0,
    "w": 224,
    "h": 288
  }
};
