/* Generated by tools/scene/build-pc.py — do not edit by hand. Boxes in % of the case picture. */
export const PC_ART = {
  "aspect": 1.1531,
  "parts": {
    "pc-gpu": {
      "src": "/assets/pc/gpu.webp",
      "box": {
        "x": 5.93,
        "y": 48.4,
        "w": 67.51,
        "h": 20.15
      },
      "hot": {
        "x": 5.93,
        "y": 48.4,
        "w": 67.51,
        "h": 20.15
      }
    },
    "pc-cooler": {
      "src": "/assets/pc/cooler.webp",
      "box": {
        "x": 16.05,
        "y": 13.58,
        "w": 28.46,
        "h": 33.18
      },
      "hot": {
        "x": 16.05,
        "y": 13.58,
        "w": 28.46,
        "h": 33.18
      }
    },
    "pc-psu": {
      "src": "/assets/pc/psu.webp",
      "box": {
        "x": 5.3,
        "y": 70.56,
        "w": 63.95,
        "h": 21.88
      },
      "hot": {
        "x": 5.45,
        "y": 70.74,
        "w": 40.47,
        "h": 21.42
      }
    }
  }
} as const;
