/* Generated by tools/rig/build-look.py — do not edit by hand. Rig coordinates (1000×1400). */
export const HAIR_FIT = {
  "sidepart": {
    "x": 376.0,
    "y": 5.0,
    "w": 255,
    "h": 182
  },
  "slick": {
    "x": 372.0,
    "y": 7.0,
    "w": 260,
    "h": 201
  },
  "shaggy": {
    "x": 362.0,
    "y": -11.0,
    "w": 280,
    "h": 209
  },
  "spiky": {
    "x": 370.0,
    "y": -4.0,
    "w": 267,
    "h": 219
  }
} as const;
/** worn clothes drawn on the rig; hats in this list also have hair variants cut under them */
export const WEAR_FIT = {
  "tee-white": {
    "slot": "SHIRT",
    "x": 187.0,
    "y": 285.5,
    "w": 624,
    "h": 481
  },
  "tee-pump": {
    "slot": "SHIRT",
    "x": 179.5,
    "y": 291.0,
    "w": 646,
    "h": 476
  },
  "jeans": {
    "slot": "PANTS",
    "x": 74.5,
    "y": 678.0,
    "w": 862,
    "h": 530
  },
  "shorts-remote": {
    "slot": "PANTS",
    "x": 179.5,
    "y": 696.5,
    "w": 652,
    "h": 291
  },
  "sneakers": {
    "slot": "SHOES",
    "x": 60.0,
    "y": 1086.0,
    "w": 882,
    "h": 270
  },
  "slippers": {
    "slot": "SHOES",
    "x": 51.5,
    "y": 1193.5,
    "w": 898,
    "h": 170
  },
  "gold-chain": {
    "slot": "ACCESSORY",
    "x": 413.5,
    "y": 291.5,
    "w": 173,
    "h": 108
  },
  "cap-moon": {
    "slot": "HEAD",
    "x": 393.0,
    "y": 13.5,
    "w": 219,
    "h": 170
  }
} as const;
export const SKIN_ORIGINAL = 1;
