/* Generated by tools/rig/build-look.py — do not edit by hand. Rig coordinates (1000×1400). */
export const HAIR_FIT = {
  "sidepart": {
    "x": 388.0,
    "y": 46.0,
    "w": 266,
    "h": 192
  },
  "slick": {
    "x": 384.0,
    "y": 47.2,
    "w": 271,
    "h": 213
  },
  "shaggy": {
    "x": 374.0,
    "y": 28.8,
    "w": 291,
    "h": 220
  },
  "spiky": {
    "x": 381.5,
    "y": 35.8,
    "w": 278,
    "h": 232
  }
} as const;
export const SKIN_ORIGINAL = 1;
