/* Generated by tools/rig/build-look.py — do not edit by hand. Rig coordinates (1000×1400). */
export const HAIR_FIT = {
  "sidepart": {
    "x": 399.7,
    "y": 40.7,
    "w": 244,
    "h": 177
  },
  "slick": {
    "x": 396.0,
    "y": 41.8,
    "w": 249,
    "h": 196
  },
  "shaggy": {
    "x": 386.8,
    "y": 24.8,
    "w": 268,
    "h": 203
  },
  "spiky": {
    "x": 393.7,
    "y": 31.3,
    "w": 256,
    "h": 213
  }
} as const;
export const SKIN_ORIGINAL = 1;
