/* generated by tools/shop/build-shop.py — boxes of the shop layers in percent of the 2000×2800 canvas */
export type ShopLayer = { left: number; top: number; width: number; height: number };
export const SHOP_ART = {
  aspect: "2000 / 2800",
  layers: {
  "room": {
    "left": 0.0,
    "top": 0.0,
    "width": 100.0,
    "height": 100.0
  },
  "lamp": {
    "left": 40.2,
    "top": 0.929,
    "width": 19.6,
    "height": 14.25
  },
  "drinks": {
    "left": 16.9,
    "top": 20.893,
    "width": 13.35,
    "height": 5.321
  },
  "rack": {
    "left": 62.35,
    "top": 24.393,
    "width": 37.05,
    "height": 32.75
  },
  "torso": {
    "left": 28.7,
    "top": 29.607,
    "width": 40.45,
    "height": 40.643
  },
  "armR": {
    "left": 56.35,
    "top": 35.214,
    "width": 18.6,
    "height": 23.5
  },
  "armL": {
    "left": 14.95,
    "top": 35.5,
    "width": 22.15,
    "height": 23.5
  },
  "head": {
    "left": 40.6,
    "top": 18.464,
    "width": 15.1,
    "height": 12.571
  },
  "sclera": {
    "left": 44.85,
    "top": 24.214,
    "width": 7.9,
    "height": 1.321
  },
  "iris": {
    "left": 45.75,
    "top": 24.214,
    "width": 6.25,
    "height": 1.25
  },
  "lids": {
    "left": 43.9,
    "top": 23.393,
    "width": 9.65,
    "height": 2.5
  },
  "cigarette": {
    "left": 46.1,
    "top": 27.714,
    "width": 2.8,
    "height": 3.071
  },
  "counter": {
    "left": 0.0,
    "top": 53.786,
    "width": 100.0,
    "height": 43.679
  },
  "weapons": {
    "left": 12.6,
    "top": 54.0,
    "width": 71.6,
    "height": 20.25
  },
  "fist": {
    "left": 45.7,
    "top": 55.571,
    "width": 20.05,
    "height": 6.786
  }
} as Record<string, ShopLayer>,
  smoke: {"x": 46.5, "y": 30.45},
  neck: {"x": 48.17, "y": 30.76},
};
